### ISSUE TITLE
value not save

### ISSUE THREAD

**Issue by re5ive** [yvoronoy/magento-extension-extra-fee#11]
when i put a number 10 any amount, value not save at all.

**Comment by franktjinaton** [comment]
Same problem.
To be specific: The Extra Fee Amount is not saved.

**Comment by Mkart** [comment]
The issue is caused by the install-0.1.1.php that is not able to create the database tables to save that data. 
Trying to execute it manually I got: Call to a member function getTable() on null in /app/code/local/Voronoy/ExtraFee/sql/voronoy_extrafee_setup/install-0.1.1.php on line 25
