### ISSUE TITLE
Cant edit the label "Extra Fee" to anything else

### ISSUE THREAD

**Issue by bilalshahab** [yvoronoy/magento-extension-extra-fee#2]
i have try setting the label to Extra charges from the magento dashboard and config.xml
but it does not change .

can you help me with this issue 

thanks in advance 

Keep up the good work

**Comment by yvoronoy** [comment]
Did you try change config in System -> Configuration -> Extra Fee Settings -> Shopping Cart Rule Extra Fee -> Label
and don't forget to flush cache.
