### ISSUE TITLE
Tax calculation is totally wrong

### ISSUE THREAD

**Issue by otto06217** [yvoronoy/magento-extension-extra-fee#3]
Hi,

my problem is:
After enabling your extension Tax calculation went totally wrong:
E.g.
Subtotal    29,29 €
Discount (3% Skonto)    -0,88 €
Shipping and Handling (Versandkosten - Deutschland) 49,00 €
Surchage    15,00 €
Total excl..Tax 67,55 €
Tax 12,36 €
Total incl. Tax 79,91 €

German Tax 19%
Magento CE 1.9,2.1
Discount will be calculated by Owebia 2.5.18

Any hint?

**Comment by yvoronoy** [comment]
Hi @otto06217 
Do you able to reproduce it on vanilla magento?

**Comment by yvoronoy** [comment]
Unable to reproduce on vanilla instance

**Comment by otto06217** [comment]
Sorry, I'm late. AFAIK I don't have a vanilla Magento.
